
name: Publish package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: git config --global user.email "github@escolalms.com" && git config --global user.name "Github"
      - run: git clean -f -n -i
      - run: npm i --legacy-peer-deps
      - run: npm run build
      - run: npm version ${{github.ref_name}}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: git push

